print ("what is your name")
name = input()
print (name)
print ("what is your email")
email = input()
print (email)
print ("ORG")
ORG = input()
print ("Access")
access = input()
print ("+---------------------------------------+")
print ("|       Apex Entertainment Pass         |")
print ("-----------------------------------------")
print ("| Attendee : " +name.ljust(27) + "|")
print ("| ORG : BCH Cybersecurity Division      |")
print ("| Contact : " +email.ljust(28) + "|")
print ("| Access : " +access.ljust(29) + "|")
print ("| Issuer : BCH Software Terminal System |")
print ("+---------------------------------------+")
