print ("what is your name")
name = input()
print (name)
print ("what is your email")
email = input()
print (email)
print ("+-----------------------------+")
print ("|  Apex Entertainment Pass    |")
print ("-------------------------------")
print ("| Attendee : " +name.ljust(17) + "|")
